### ISSUE TITLE
1. Introduction - Minor Errors, Style Guide Question

### ISSUE THREAD

**Issue by pomfy113** [MakeSchool-Tutorials/sa-2018-landing-page#2]
> By the end of this tutorial, you will:
> 
> - build responsive websites using HTML, CSS, and Bootstrap
> - ...

Should beginnings of bullets be capitalized?

> Soon enough, **you've** be able to build websites

Replace 'you've' to 'you'll'.

**Comment by ocwang** [comment]
For bullet point capitalization, it's a stylistic choice. We should update our style guide so whatever is chosen will remain consistent throughout each tutorials.

For typos and grammatical errors, go ahead and submit a pull request to the Github repo so they can be reviewed and accepted. (Unless @dionlarson has specified otherwise.)
